name = "fullstack-pages"
compatibility_date = "2025-06-25"

[build]
command = "npm run build"
cwd = "./frontend/"
upload = { dir = "frontend/dist" }

[site]
bucket = "frontend/dist"

#[[containers]]
#class_name = "Api"
#image = "./backend/Dockerfile"
#instance_type = "basic"

[vars]
ASSETS = "KV_ASSETS"
